--insert into ingredients (id, ingredient_names) values(11, '5 pomidorow');
--insert into ingredients (id, ingredient_names) values(12, 'szczypta soli');
--insert into ingredients (id, ingredient_names) values(13, 'wloszczyzna');
--insert into ingredients (id, ingredient_names) values(14, 'kosc wolowa');
